### ISSUE TITLE
Text (vertical margin and styles)

### ISSUE THREAD

**Issue by laxyapahuja** [Practikality/post-x#6]
Add more options to add text boxes. Keep 5 fixed positions -> Top right, Bottom right, Top left, Center, Bottom left. Apart from the default text boxes, allow a user to create a new one. When he clicks on the `add` button, ask him to select from one of the 2 remaining positions

**Comment by padamchopra** [comment]
This feature will not affect postx in a major way. Moreover, it will drive us away from our main objective of creating a simple to use yet customizable social media post generator
