### ISSUE TITLE
The color change when uploading posts on Facebook

### ISSUE THREAD

**Issue by laxyapahuja** [Practikality/post-x#8]
When you share a post on Facebook, it compresses the image and because of that the quality gets decreased and the colors look different. It can be solved maybe by increasing the quality and resolution of the posts.

**Comment by padamchopra** [comment]
This actually depends on the screen resolution of the phone, so consider upgrading to a better one :wink:

**Comment by laxyapahuja** [comment]
No. You don't seem to get it.
